# Generated by Django 4.1.3 on 2022-12-01 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PublicUser",
            fields=[
                ("user_no", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(default="Anonymous", max_length=50)),
                ("last_name", models.CharField(default="User", max_length=50)),
                ("email", models.EmailField(default="No email", max_length=100)),
                ("remarks", models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Vulnerabilities",
            fields=[
                ("vul_no", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Awaiting Approval", "Awaiting approval"),
                            ("Assigned", "Assigned"),
                            ("Rejected", "Rejected"),
                            ("Fixed", "Fixed"),
                            ("Escalated", "Escalated"),
                        ],
                        default="Awaiting Approval",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_to",
                    models.CharField(
                        choices=[
                            ("Unassigned", "Unassigned"),
                            ("General Affairs", "General Affairs"),
                            (
                                "Agriculture, Nature and Food Quality",
                                "Agriculture, Nature and Food Quality",
                            ),
                            ("Defence", "Defence"),
                            ("Economic Affairs", "Economic Affairs"),
                            ("Education", "Education"),
                            ("Finance", "Finance"),
                            ("Foreign Affairs", "Foreign Affairs"),
                            ("Health, Welfare and sport", "Health, Welfare and sport"),
                            ("Infrastructure", "Infrastructure"),
                            (
                                "Interior and Kingdom relations",
                                "Interior and Kingdom relations",
                            ),
                            ("Justice and Security", "Justice and Security"),
                            (
                                "Social Affairs and Employment",
                                "Social Affairs and Employment",
                            ),
                            ("Escalation Team", "Escalation Team"),
                        ],
                        default="Unassigned",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("vulnerable_website", models.URLField()),
                ("date_time", models.DateTimeField(max_length=50)),
                ("description", models.TextField(max_length=1000)),
                ("replicate", models.TextField(max_length=1000)),
                ("exploit_code", models.TextField(blank=True, max_length=2000)),
                ("potential_fix", models.TextField(blank=True, max_length=1000)),
                ("video", models.URLField(blank=True)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="report.publicuser",
                    ),
                ),
            ],
        ),
    ]
