# Generated by Django 4.1.3 on 2022-11-14 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicUser',
            fields=[
                ('user_no', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('vulnerability_no', models.AutoField(primary_key=True, serialize=False)),
                ('vulnerable_website', models.URLField()),
                ('date_time', models.DateTimeField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('replicate', models.CharField(max_length=1000)),
                ('exploit_code', models.CharField(max_length=2000)),
                ('potential_fix', models.CharField(max_length=1000)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.publicuser')),
            ],
        ),
    ]
