# Generated by Django 4.1.3 on 2022-11-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerabilities',
            name='status',
            field=models.TextField(default='Waiting approval'),
        ),
    ]
