# Generated by Django 4.1.3 on 2022-11-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnurability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(default='Awaiting approval', max_length=25)),
                ('Assigned_to', models.CharField(default='Unassigned', max_length=100)),
                ('Description', models.CharField(max_length=200)),
                ('Website_link', models.CharField(max_length=100)),
                ('Date_and_time', models.CharField(max_length=100)),
                ('How_to_replicate', models.CharField(max_length=200)),
                ('Exploit_code', models.CharField(max_length=100)),
                ('Potential_fix', models.CharField(max_length=200)),
                ('Video_link', models.CharField(max_length=100)),
                ('Comment', models.CharField(max_length=200)),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Email_address', models.CharField(max_length=200)),
            ],
        ),
    ]
