# Generated by Django 4.1.3 on 2022-11-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operatorview', '0003_alter_vulnurability_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporter',
            name='Email_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='First_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='Last_name',
            field=models.CharField(max_length=100),
        ),
    ]
