# Generated by Django 4.1.3 on 2022-11-15 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operatorview', '0004_alter_reporter_email_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnurability',
            name='Assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operatorview.department'),
        ),
        migrations.AlterField(
            model_name='vulnurability',
            name='Reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operatorview.reporter'),
        ),
    ]
