# Generated by Django 4.1.3 on 2022-11-15 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operatorview', '0005_alter_vulnurability_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnurability',
            name='Assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Dept', to='operatorview.department'),
        ),
        migrations.AlterField(
            model_name='vulnurability',
            name='Reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Publicuser', to='operatorview.reporter'),
        ),
    ]
