# Generated by Django 4.1.3 on 2022-11-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operatorview', '0006_alter_vulnurability_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vulnurability',
            name='Reported_by',
        ),
        migrations.AddField(
            model_name='vulnurability',
            name='Email_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vulnurability',
            name='First_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vulnurability',
            name='Last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vulnurability',
            name='Status',
            field=models.CharField(choices=[('AA', 'Awaiting approval'), ('AS', 'Assigned'), ('R', 'Rejected'), ('F', 'Fixed'), ('E', 'Escalated')], max_length=25),
        ),
        migrations.DeleteModel(
            name='Reporter',
        ),
    ]
