# Generated by Django 4.1.3 on 2022-11-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operatorview', '0007_remove_vulnurability_reported_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnurability',
            name='Status',
            field=models.CharField(choices=[('AA', 'Awaiting approval'), ('AS', 'Assigned'), ('R', 'Rejected'), ('F', 'Fixed'), ('E', 'Escalated')], default='AA', max_length=25),
        ),
    ]
