# Generated by Django 4.1.3 on 2022-11-16 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operatorview', '0009_alter_vulnurability_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicUser',
            fields=[
                ('user_no', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='Anonymous', max_length=50)),
                ('last_name', models.CharField(default='User', max_length=50)),
                ('email', models.EmailField(default='No email', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VulnerabilitiesOP',
            fields=[
                ('vul_no', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Awaiting Approval', 'Awaiting approval'), ('Assigned', 'Assigned'), ('Rejected', 'Rejected'), ('Fixed', 'Fixed'), ('Escalated', 'Escalated')], default='Awaiting Approval', max_length=20)),
                ('vulnerable_website', models.URLField()),
                ('date_time', models.DateTimeField(max_length=50)),
                ('replicate', models.TextField(max_length=1000)),
                ('exploit_code', models.TextField(blank=True, max_length=2000)),
                ('potential_fix', models.TextField(blank=True, max_length=1000)),
                ('video', models.URLField(blank=True)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='operatorview.publicuser')),
            ],
        ),
        migrations.RemoveField(
            model_name='vulnurability',
            name='Assigned_to',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Vulnurability',
        ),
    ]
