# Generated by Django 4.1.3 on 2022-11-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operatorview', '0011_vulnerabilitiesop_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerabilitiesop',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
