# Generated by Django 4.1.3 on 2022-11-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operatorview', '0012_alter_vulnerabilitiesop_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerabilitiesop',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
