# Generated by Django 4.1.3 on 2022-11-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operatorview', '0013_vulnerabilitiesop_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerabilitiesop',
            name='assigned_to',
            field=models.CharField(choices=[('Unassigned', 'Unassigned'), ('General Affairs', 'General Affairs'), ('Agriculture, Nature and Food Quality', 'Agriculture, Nature and Food Quality'), ('Defence', 'Defence'), ('Economic Affairs', 'Economic Affairs'), ('Education', 'Education'), ('Finance', 'Finance'), ('Foreign Affairs', 'Foreign Affairs'), ('Health, Welfare and sport', 'Health, Welfare and sport'), ('Infrastructure', 'Infrastructure'), ('Interior and Kingdom relations', 'Interior and Kingdom relations'), ('Justice and Security', 'Justice and Security'), ('Social Affairs and Employment', 'Social Affairs and Employment'), ('Escalated', 'Escalation Team')], default='Unassigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='vulnerabilitiesop',
            name='status',
            field=models.CharField(choices=[('Awaiting Approval', 'Awaiting approval'), ('Assigned', 'Assigned'), ('Rejected', 'Rejected'), ('Fixed', 'Fixed'), ('Escalated', 'Escalation Team')], default='Awaiting Approval', max_length=20),
        ),
    ]
