# Generated by Django 4.1.3 on 2022-11-25 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operatorview', '0015_alter_vulnerabilitiesop_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vulnerabilitiesop',
            name='reported_by',
        ),
        migrations.DeleteModel(
            name='PublicUser',
        ),
        migrations.DeleteModel(
            name='VulnerabilitiesOP',
        ),
    ]
